"""
agent.py — LangChain SQL Agent backed by Anthropic Claude.

The agent has two tools:
  - run_sql(query)            → executes SQL on transactions.db, returns JSON rows
  - make_chart(type, sql, title) → runs SQL, builds a Plotly figure, stored
                                   in _pending_chart so the caller can retrieve it

Public API:
    from agent import query_agent
    result = query_agent("how much did I spend in January?")
    # result = {"text": str, "chart": plotly.Figure | None, "suggestions": list[str]}
"""

import os
import sqlite3
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.tools import tool
from typing import Optional

from langchain_anthropic import ChatAnthropic

# langchain 1.x uses create_agent (langgraph-based);
# fall back to legacy AgentExecutor for langchain 0.x
try:
    from langchain.agents import create_agent          # langchain >=1.0
    _USE_LANGGRAPH = True
except ImportError:
    from langchain.agents import AgentExecutor, create_tool_calling_agent  # langchain <1.0
    from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
    _USE_LANGGRAPH = False

# Load .env from the backend directory (works from any working directory)
_BACKEND_DIR = Path(__file__).resolve().parent
load_dotenv(_BACKEND_DIR / ".env", override=True)

DB_PATH = str(_BACKEND_DIR / "data" / "transactions.db")

# Stores the last chart generated by the make_chart tool (side-effect pattern)
_pending_chart: dict = {"figs": []}


# ─────────────────────────────────────────────────────────────────────────────
# TOOLS
# ─────────────────────────────────────────────────────────────────────────────

@tool
def run_sql(query: str) -> str:
    """
    Execute a SQL SELECT query on the transactions database and return results as JSON.

    Table: transactions
    Columns:
      transaction_id, account_id, merchant_name, merchant_id,
      timestamp (TEXT, format YYYY-MM-DD HH:MM:SS),
      transaction_description, category, amount (REAL, EUR),
      currency, predicted_category, confidence, correct,
      year (INT), month (INT 1-12), day (INT)

    Categories: Food & Dining, Transportation, Entertainment & Recreation,
    Shopping & Retail, Financial Services, Healthcare & Medical,
    Utilities & Services, Income, Government & Legal, Charity & Donations

    To filter expenses only: WHERE predicted_category != 'Income'
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql_query(query, conn)
        conn.close()
        if df.empty:
            return "No results found for this query."
        return df.head(100).to_json(orient="records", date_format="iso")
    except Exception as e:
        return f"SQL Error: {e}"


@tool
def make_chart(chart_type: str, sql_query: str, title: str = "") -> str:
    """
    Create a Plotly chart from a SQL query and store it for the frontend.

    chart_type : 'bar' | 'line' | 'donut'
    sql_query  : SQL that returns exactly two columns → (label/x, value/y)
    title      : chart title shown to the user

    Use this whenever the user asks for a graph, chart, or when showing
    trends over time or category breakdowns would be helpful.
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql_query(sql_query, conn)
        conn.close()

        if df.empty:
            return "No data to chart."

        cols = df.columns.tolist()
        x_col = cols[0]
        y_col = cols[1] if len(cols) > 1 else cols[0]

        # Keep only the two relevant columns, then aggregate duplicate labels
        df = df[[x_col, y_col]].copy()
        if df[x_col].duplicated().any():
            df = df.groupby(x_col, sort=False)[y_col].sum().reset_index()

        # Convert month numbers → short names for readability
        MONTH_NAMES = {1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",
                       7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"}
        if df[x_col].dtype in ["int64","float64"]:
            unique_vals = df[x_col].dropna().unique()
            if set(unique_vals).issubset(set(range(1, 13))):
                df = df.copy()
                df[x_col] = df[x_col].map(lambda m: MONTH_NAMES.get(int(m), str(m)))

        BG   = "#FAFAF8"
        GRID = "#EDEBE5"

        LAYOUT = dict(
            height=340,
            paper_bgcolor=BG,
            plot_bgcolor=BG,
            font=dict(family="DM Sans", size=13, color="#1A1916"),
            margin=dict(t=48, b=72, l=64, r=24),
            title=dict(
                text=f"<b>{title}</b>",
                font=dict(family="DM Sans", size=14, color="#1A1916"),
                x=0, xanchor="left",
            ),
            hoverlabel=dict(
                bgcolor="#1A1916", font_color="#fff",
                font_family="DM Sans", font_size=12,
                bordercolor="#1A1916",
            ),
        )

        CAT_COLORS = {
            "Food & Dining":              "#E8860C",
            "Transportation":             "#2E6BC6",
            "Entertainment & Recreation": "#8B3AA0",
            "Shopping & Retail":          "#C4881D",
            "Financial Services":         "#888888",
            "Healthcare & Medical":       "#D94444",
            "Utilities & Services":       "#3A6A9B",
            "Income":                     "#2A9D6A",
            "Government & Legal":         "#5A6070",
            "Charity & Donations":        "#C44A7A",
        }

        MONTH_SET = {"Jan","Feb","Mar","Apr","May","Jun",
                     "Jul","Aug","Sep","Oct","Nov","Dec"}

        bar_colors = [CAT_COLORS.get(str(lbl), None) for lbl in df[x_col]]
        has_cat_colors = any(c is not None for c in bar_colors)

        # Detect time-series: labels are months, years, or year-month strings
        labels_str = [str(l) for l in df[x_col]]
        is_time_series = (
            set(labels_str).issubset(MONTH_SET) or
            all(str(l).isdigit() and (1900 < int(l) < 2100) for l in labels_str) or
            all("-" in str(l) or "/" in str(l) for l in labels_str)
        )

        if has_cat_colors:
            bar_colors = [c or "#AAAAAA" for c in bar_colors]
        elif is_time_series:
            # Single consistent color for time-based charts
            bar_colors = ["#2E6BC6"] * len(df)
        else:
            # Distinct colors for non-category, non-time data (e.g. merchants)
            PALETTE = ["#1A1916","#E8860C","#2E6BC6","#8B3AA0",
                       "#C4881D","#D94444","#3A6A9B","#2A9D6A"]
            bar_colors = [PALETTE[i % len(PALETTE)] for i in range(len(df))]

        if chart_type == "bar":
            # Use horizontal bars when labels are long (categories) or many items
            avg_label_len = sum(len(str(l)) for l in df[x_col]) / max(len(df), 1)
            use_horizontal = avg_label_len > 8 or len(df) > 5

            if use_horizontal:
                # Sort ascending so biggest is at top
                df_sorted = df.sort_values(y_col, ascending=True)
                h_colors = [CAT_COLORS.get(str(lbl), None) for lbl in df_sorted[x_col]]
                h_colors = [c or PALETTE[i % len(PALETTE)] for i, c in enumerate(h_colors)]
                fig = go.Figure(data=[go.Bar(
                    y=df_sorted[x_col], x=df_sorted[y_col],
                    orientation="h",
                    marker_color=h_colors,
                    marker_line_width=0,
                    text=[f"€{v:,.0f}" for v in df_sorted[y_col]],
                    textposition="outside",
                    textfont=dict(size=11, color="#1A1916", family="DM Sans"),
                    cliponaxis=False,
                    hovertemplate="<b>%{y}</b><br>€%{x:,.0f}<extra></extra>",
                )])
                fig.update_layout(**LAYOUT)
                max_val = df_sorted[y_col].max()
                fig.update_layout(
                    height=max(300, len(df) * 48 + 90),
                    margin=dict(t=48, b=24, l=170, r=100),
                    xaxis=dict(
                        showgrid=True, gridcolor=GRID, gridwidth=1,
                        zeroline=False, showline=False,
                        tickprefix="€", tickformat=",.0f",
                        tickfont=dict(size=12, color="#1A1916"),
                        range=[0, max_val * 1.40],
                    ),
                    yaxis=dict(
                        showgrid=False, showline=False,
                        tickfont=dict(size=12, color="#1A1916"),
                        automargin=True,
                    ),
                    bargap=0.28,
                )
            else:
                fig = go.Figure(data=[go.Bar(
                    x=df[x_col], y=df[y_col],
                    marker_color=bar_colors,
                    marker_line_width=0,
                    text=[f"€{v:,.0f}" for v in df[y_col]],
                    textposition="outside",
                    textfont=dict(size=11, color="#1A1916", family="DM Sans"),
                    hovertemplate="<b>%{x}</b><br>€%{y:,.0f}<extra></extra>",
                )])
                fig.update_layout(**LAYOUT)
                max_val = df[y_col].max()
                fig.update_layout(
                    xaxis=dict(
                        showgrid=False, showline=False,
                        tickangle=-35, automargin=True,
                        tickfont=dict(size=12, color="#1A1916"),
                    ),
                    yaxis=dict(
                        showgrid=True, gridcolor=GRID, gridwidth=1,
                        zeroline=False, showline=False,
                        tickprefix="€", tickformat=",.0f",
                        tickfont=dict(size=12, color="#1A1916"),
                        range=[0, max_val * 1.20],
                    ),
                    bargap=0.35,
                )

        elif chart_type == "line":
            fig = go.Figure()
            show_labels = len(df) <= 14
            fig.add_trace(go.Scatter(
                x=df[x_col], y=df[y_col],
                mode="lines+markers+text" if show_labels else "lines+markers",
                line=dict(color="#1A1916", width=2.5, shape="spline", smoothing=0.4),
                marker=dict(size=5 if not show_labels else 7, color="#1A1916",
                            line=dict(color=BG, width=2)),
                fill="tozeroy",
                fillcolor="rgba(26,25,22,0.06)",
                **(dict(
                    text=[f"€{v:,.0f}" for v in df[y_col]],
                    textposition="top center",
                    textfont=dict(size=10, color="#1A1916"),
                ) if show_labels else {}),
                hovertemplate="<b>%{x}</b><br>€%{y:,.0f}<extra></extra>",
            ))
            fig.update_layout(**LAYOUT)
            fig.update_layout(
                xaxis=dict(
                    showgrid=False, showline=False,
                    tickangle=-35, automargin=True,
                    tickfont=dict(size=12, color="#1A1916"),
                ),
                yaxis=dict(
                    showgrid=True, gridcolor=GRID, gridwidth=1,
                    zeroline=False, showline=False,
                    tickprefix="€", tickformat=",.0f",
                    tickfont=dict(size=12, color="#1A1916"),
                ),
            )

        elif chart_type == "donut":
            DONUT_PALETTE = [
                "#1A1916", "#E8860C", "#2E6BC6", "#8B3AA0",
                "#C4881D", "#D94444", "#3A6A9B", "#2A9D6A",
                "#C44A7A", "#5A6070", "#F0A500", "#4A90D9",
            ]
            raw_colors = [CAT_COLORS.get(str(lbl), None) for lbl in df[x_col]]
            has_any = any(c is not None for c in raw_colors)
            if has_any:
                colors = [c or "#AAAAAA" for c in raw_colors]
            else:
                # Non-category labels (merchants, etc.) → use distinct palette
                colors = [DONUT_PALETTE[i % len(DONUT_PALETTE)] for i in range(len(df))]
            total = df[y_col].sum()
            fig = go.Figure(data=[go.Pie(
                labels=df[x_col],
                values=df[y_col],
                hole=0.58,
                marker_colors=colors,
                marker_line=dict(color=BG, width=2),
                textinfo="percent",
                textfont=dict(size=11, family="DM Sans"),
                hovertemplate="<b>%{label}</b><br>€%{value:,.0f}<br>%{percent}<extra></extra>",
                sort=True,
            )])
            fig.update_layout(**LAYOUT)
            fig.update_layout(
                margin=dict(t=48, b=16, l=16, r=16),
                showlegend=True,
                legend=dict(
                    orientation="v", x=1.02, y=0.5,
                    font=dict(size=11, family="DM Sans", color="#1A1916"),
                    itemsizing="constant",
                ),
                annotations=[dict(
                    text=f"<b>€{total:,.0f}</b>",
                    x=0.5, y=0.5, showarrow=False,
                    font=dict(size=15, family="DM Sans", color="#1A1916"),
                    xanchor="center",
                )],
            )

        else:
            fig = go.Figure(data=[go.Bar(
                x=df[x_col], y=df[y_col],
                marker_color="#1A1916", marker_line_width=0,
            )])
            fig.update_layout(**LAYOUT)

        _pending_chart["figs"].append(fig)
        return f"Chart '{title}' created successfully."

    except Exception as e:
        return f"Chart error: {e}"


# ─────────────────────────────────────────────────────────────────────────────
# SYSTEM PROMPT
# ─────────────────────────────────────────────────────────────────────────────

_SYSTEM_PROMPT_TEMPLATE = """You are Fynn, a friendly AI financial assistant for {user_name}.
You have access to {user_name}'s personal transaction history via two tools.
{budget_section}
{language_section}
## Workflow
1. ALWAYS call run_sql first to get real data before answering. NEVER assume or hardcode any facts about the user — discover everything from the data.
2. Call make_chart when showing trends, breakdowns, or comparisons over time.
3. Reply in the same language the user writes in.

## Database schema
The `transactions` table has these columns:
  transaction_id, account_id, source, merchant_name, merchant_id,
  timestamp, transaction_description, category, amount, currency,
  predicted_category, confidence, correct, year, month, day

There is also an `investments` table:
  ticker, company_name, asset_type, purchase_date, purchase_price, quantity, total_cost, currency

## SQL rules — SIGNED AMOUNTS (CRITICAL)
- `amount` is SIGNED: **negative** for expenses, **positive** for income.
  - Expenses: WHERE amount < 0   (use ABS(amount) to get the positive value)
  - Income:   WHERE predicted_category = 'Income' (amount is positive)
- Special categories to EXCLUDE from spending/income analysis:
  - 'Transfer' — money moving between the user's own accounts
  - 'Investment' — investment purchases
  - Always add: AND predicted_category NOT IN ('Transfer', 'Investment')
- IMPORTANT — category analysis: some categories may contain mixed merchant types.
  When asked about "biggest expense" or "top category", always drill down to the merchant level
  (GROUP BY merchant_name) to give accurate answers. A single large merchant (e.g. rent) inside
  a category can dominate — identify and report it separately rather than attributing everything
  to the category name.
- Multi-bank: the `source` column identifies the bank (e.g. 'CaixaBank', 'Revolut', etc.)
- Filter periods with integer columns: `year` (e.g. 2023) and `month` (1–12).
- Merchant search: WHERE LOWER(merchant_name) LIKE '%keyword%'
- IMPORTANT — "last week" / "last month" / "recently": the dataset may NOT include today's date.
  Always determine the most recent data available first:
  - "last month"  → WHERE year = (SELECT MAX(year) FROM transactions) AND month = (SELECT MAX(month) FROM transactions WHERE year=(SELECT MAX(year) FROM transactions))
  - "last week"   → WHERE DATE(timestamp) >= DATE((SELECT MAX(timestamp) FROM transactions), '-7 days')
  - "this year"   → WHERE year = (SELECT MAX(year) FROM transactions)

## Semantic understanding (CRITICAL)
When the user asks about a concept, use SQL to discover the relevant data rather than assuming specific merchants or categories.
- groceries / supermarket → query: SELECT DISTINCT merchant_name FROM transactions WHERE predicted_category='Food & Dining' AND amount < 0 GROUP BY merchant_name HAVING AVG(ABS(amount)) > 30 AND COUNT(*) > 10 — these are likely supermarkets (high frequency, moderate amounts). Cross-reference with common supermarket name patterns.
- dining out / restaurants / bars → Food & Dining merchants that are NOT supermarkets (lower frequency per merchant, smaller average amounts)
- clothes / fashion → predicted_category = 'Shopping & Retail', then filter by merchant names that suggest clothing stores
- subscriptions / recurring → find merchants with exactly 1 charge per month, consistent amount (< €1 variance between months), appearing in at least 2 of the last 3 months, active in the most recent month. Exclude rent and insurance. Include telecom/internet as subscriptions.
- rent / housing → look for the largest single recurring monthly expense (same merchant, same amount every month, high amount)
- transport / commute → predicted_category = 'Transportation'
- health / medical → predicted_category = 'Healthcare & Medical'
- utilities / bills → predicted_category = 'Utilities & Services'
- transfers → predicted_category = 'Transfer' (internal, between user's own accounts)
- investments / portfolio → predicted_category = 'Investment' OR query the investments table
- income / salary → predicted_category = 'Income' or WHERE amount > 0
If unsure about a concept, run exploratory queries (e.g. SELECT DISTINCT merchant_name, COUNT(*) ...) to discover the relevant merchants before answering.

## Response formatting (CRITICAL)
- Use **bold** for key numbers and amounts (e.g. **€1,234**)
- Use bullet points (- item) for lists, max 5–6 items
- NEVER list individual transactions inline as text — summarize them or use make_chart
- For "show me transactions" queries: show top 5–6 with merchant + amount, then summarize the rest
- Keep responses to 3–6 lines max. Be concise.
- Format amounts as €X,XXX or €X,XXX.XX
- When showing expense amounts, show them as positive (remove the negative sign)

## Chart guidance
- Use `bar` for category breakdowns or month comparisons
- Use `line` for trends over time (monthly/yearly)
- Use `donut` for percentage breakdowns by category
- SQL for charts must return exactly 2 columns: (label, value)
- For spending charts, use ABS(amount) so bars/values are positive
"""


def _build_system_prompt(user_context: dict = None) -> str:
    """Build the system prompt dynamically from user preferences."""
    ctx = user_context or {}
    user_name = ctx.get("user_name") or "the user"
    language = ctx.get("language") or "English"
    monthly_budget = ctx.get("monthly_budget")

    budget_section = ""
    if monthly_budget:
        alert_threshold = ctx.get("alert_threshold") or 80
        threshold_amount = monthly_budget * alert_threshold / 100
        budget_section = (
            f"\n## Budget\n"
            f"{user_name}'s monthly budget is **€{monthly_budget:,.0f}**.\n"
            f"Their warning threshold is **{alert_threshold:.0f}%** of budget (= **€{threshold_amount:,.0f}**).\n"
            f"When giving financial advice, reference this budget. "
            f"If spending exceeds €{threshold_amount:,.0f} (i.e. {alert_threshold:.0f}% of the budget), warn {user_name} that they are approaching their limit. "
            f"If under that threshold, encourage them.\n"
        )

    language_section = f"\n## Language preference\n{user_name}'s preferred language is {language}. Default to this language unless the user writes in a different language.\n"

    return _SYSTEM_PROMPT_TEMPLATE.format(
        user_name=user_name,
        budget_section=budget_section,
        language_section=language_section,
    )


# Keep a default for backward compatibility
SYSTEM_PROMPT = _build_system_prompt()


# ─────────────────────────────────────────────────────────────────────────────
# AGENT SETUP
# ─────────────────────────────────────────────────────────────────────────────

_agent_executor = None  # the compiled agent (langgraph graph or AgentExecutor)


def _make_executor(model: str = "claude-haiku-4-5-20251001", user_context: dict = None):
    """Build the agent using Claude (Anthropic)."""
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY not set in .env")
    llm = ChatAnthropic(
        model=model,
        anthropic_api_key=api_key,
        temperature=0,
        max_tokens=2048,
    )
    tools = [run_sql, make_chart]
    sys_prompt = _build_system_prompt(user_context)

    if _USE_LANGGRAPH:
        # langchain >=1.0: create_agent returns a CompiledStateGraph
        return create_agent(model=llm, tools=tools, system_prompt=sys_prompt)
    else:
        # langchain <1.0: legacy AgentExecutor
        prompt = ChatPromptTemplate.from_messages([
            ("system", sys_prompt),
            MessagesPlaceholder("chat_history", optional=True),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ])
        agent = create_tool_calling_agent(llm, tools, prompt)
        return AgentExecutor(agent=agent, tools=tools, verbose=True, max_iterations=8)


def _build_agent(user_context: dict = None):
    return _make_executor(user_context=user_context)


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _extract_text(output) -> str:
    """
    Claude (via langchain-anthropic) sometimes returns output as:
      - a plain string  → use as-is
      - a list of content blocks: [{'type':'text','text':'...','index':0}]
      - a stringified version of the above
    This helper normalises all cases to a plain string.
    """
    if not output:
        return "Sorry, I couldn't find an answer."

    # Already a clean string
    if isinstance(output, str):
        # Check if it looks like a stringified list of content blocks
        stripped = output.strip()
        if stripped.startswith("[{") or stripped.startswith("[{'"):
            try:
                import ast
                blocks = ast.literal_eval(stripped)
                if isinstance(blocks, list):
                    parts = [b.get("text", "") for b in blocks if isinstance(b, dict) and b.get("type") == "text"]
                    joined = "\n".join(parts).strip()
                    if joined:
                        return joined
            except Exception:
                pass
        return output

    # List of content block dicts
    if isinstance(output, list):
        parts = [b.get("text", "") for b in output if isinstance(b, dict) and b.get("type") == "text"]
        joined = "\n".join(parts).strip()
        return joined if joined else str(output)

    return str(output)


# ─────────────────────────────────────────────────────────────────────────────
# PUBLIC API
# ─────────────────────────────────────────────────────────────────────────────

def query_agent(user_message: str, chat_history: list = None, callbacks: list = None, user_context: dict = None) -> dict:
    """
    Send a message to the agent and return a response dict compatible
    with the Streamlit frontend:

        {
            "text":        str,
            "chart":       plotly.Figure | None,
            "table":       None,
            "suggestions": list[str],
        }

    chat_history: list of {"role": "user"|"bot", "text": str} dicts
    user_context: {"user_name": str, "language": str, "monthly_budget": float}
    """
    global _agent_executor, _pending_chart

    # Reset chart state before each call
    _pending_chart["figs"] = []

    # Rebuild agent if user context provided (personalized system prompt)
    if user_context and any(v for v in user_context.values()):
        _agent_executor = _build_agent(user_context)
    elif _agent_executor is None:
        _agent_executor = _build_agent()

    # Build LangChain message history (last 6 messages = 3 exchanges)
    lc_history = []
    if chat_history:
        for msg in chat_history[-6:]:
            if msg.get("role") == "user":
                lc_history.append(HumanMessage(content=msg["text"]))
            elif msg.get("role") == "bot":
                lc_history.append(AIMessage(content=msg["text"]))

    last_error = None
    text = None
    _pending_chart["figs"] = []

    try:
        if _agent_executor is None:
            _agent_executor = _make_executor()

        cfg = {"callbacks": callbacks} if callbacks else {}

        if _USE_LANGGRAPH:
            # langchain >=1.0: invoke with {"messages": [...]}
            messages = lc_history + [HumanMessage(content=user_message)]
            result = _agent_executor.invoke({"messages": messages}, config=cfg)
            # Extract text from the last AI message
            out_messages = result.get("messages", [])
            ai_text = ""
            for m in reversed(out_messages):
                if isinstance(m, AIMessage) and isinstance(m.content, str) and m.content.strip():
                    ai_text = m.content
                    break
                elif isinstance(m, AIMessage) and isinstance(m.content, list):
                    # Content blocks format
                    parts = [b.get("text", "") for b in m.content if isinstance(b, dict) and b.get("type") == "text"]
                    joined = "\n".join(parts).strip()
                    if joined:
                        ai_text = joined
                        break
            text = _extract_text(ai_text)
        else:
            # langchain <1.0: legacy AgentExecutor
            result = _agent_executor.invoke({
                "input": user_message,
                "chat_history": lc_history,
            }, config=cfg)
            text = _extract_text(result.get("output", ""))
    except Exception as e:
        last_error = e
        text = f"Sorry, something went wrong. Try rephrasing your question. ({last_error})"

    charts = _pending_chart.get("figs", [])
    _pending_chart["figs"] = []  # clean up

    return {
        "text": text,
        "charts": charts,
        "chart": charts[0] if charts else None,
        "table": None,
        "suggestions": _suggest(user_message),
    }


def _suggest(msg: str) -> list:
    """Return contextual follow-up chips based on the user's message."""
    msg = msg.lower()
    if any(w in msg for w in ["categor", "breakdown", "donut"]):
        return ["Monthly trend", "Top merchants", "Compare months"]
    if any(w in msg for w in ["month", "trend", "compar"]):
        return ["Show by category", "Top merchants", "Subscriptions"]
    if any(w in msg for w in ["merchant", "shop", "store"]):
        return ["Show by category", "Monthly summary", "Budget tips"]
    return ["Monthly summary", "Top categories", "Show subscriptions", "Budget tips"]
